# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Partnership Garden
email: partnershipgarden@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  <strong>The Partnership Garden </strong>
  is a permaculture-focused community garden in Apple Valley, Minnesota
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://partnershipgarden.org" # the base hostname & protocol for your site
twitter_username: null
github_username:  partnershipgarden

# Build settings
markdown: kramdown
